# Generated by Django 4.2.17 on 2025-01-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usermodel',
            new_name='usermode',
        ),
    ]
