# Generated by Django 4.2.17 on 2025-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_jobpostmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='aplliedjobsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ph', models.CharField(max_length=10)),
                ('dob', models.DateTimeField()),
                ('hq', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('jobname', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='')),
                ('userid', models.CharField(max_length=10)),
            ],
        ),
    ]
