# Generated by Django 5.1.4 on 2025-03-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_aplliedjobsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobpostmodel',
        ),
    ]
