# Generated by Django 5.1.4 on 2025-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_delete_jobpostmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpostmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jobname', models.CharField(max_length=30)),
                ('work', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('jobtype', models.CharField(max_length=20)),
                ('job_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
